<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
		*
		{
			margin: 0;
			padding: 0;
		}
		body
		{
			background-color:#dedede;
		}
		#Header
		{
			display: flex;
			align-items: center;
			justify-content: center;
			width: 100vw;
			height: 8vh;
			background-color: black;
			color: white;
		}
		#HeaderTitle
		{
			text-transform: uppercase;
			font-family: Calibri;
		}
		#Content
		{
			margin: 2vw;
		}
	</style>
</head>
<body>
	<header id = "Header">
		<h1 id = "HeaderTitle">Miniframework</h1>
	</header>
	<section id = "Content">
		<?php 
			$this->content();
		?>
	</section>
</body>
</html>