<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<style>
		*
		{
			margin:0;
			padding: 0;
		}
		#Header
		{
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
			background-color: black;
			width: 100vw;
			height: 8vh;
		}
		#HeaderTitle
		{
			font-size: 2.1em;
		}
		#Content
		{
			background-color: #4089ff;
			padding: 2vw;
			color: black;
		}
		.ContentTitle
		{
			text-align: center;
			text-transform: uppercase;
			text-shadow: 4px 4px 4px black;
			color: white;
		}
	</style>
</head>
<body>
	<header id = "Header">
		<h1 id = "HeaderTitle">MINI FRAMEWORK</h1>
	</header>
	<section id = "Content">
		<h1 class = "ContentTitle">LAYOUT Padrão</h1>
		<?php $this->content()?>	
	</section>
</body>
</html>